# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sage Wright
tagline:          'Bioinformatics Scientist'
description:      'Bioinformatics Scientist'
domain:           sage-wright.github.io
url:              https://sage-wright.github.io  
baseurl:          https://sage-wright.github.io/

author:
  name:           'Sage Wright'
  url:            https://twitter.com/bioinfo_sage

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/sage-wright
